// packages/ui/src/components/_common/statut.tsx
import { Couleur } from 'camino-common/src/static/couleurs'
import { DomaineId } from 'camino-common/src/static/domaines'
import { Pill } from '../_ui/pill'

export interface Props {
  color?: Couleur | `domaine-${DomaineId}`
  nom?: string
}

export function Statut(props: Props) {
  return (
    <Pill color={`bg-${props.color ?? 'neutral'}`}>
      {props.nom ?? 'indéfini'}
    </Pill>
  )
}

// packages/ui/src/components/_common/statut.vue
<template>
  <Pill :color="`bg-${color}`">
    {{ nom }}
  </Pill>
</template>

<script setup lang="ts">
import Pill from '../_ui/pill.vue'
import { withDefaults } from 'vue'

withDefaults(
  defineProps<{
    color?: string
    nom?: string
  }>(),
  { color: 'neutral', nom: 'indéfini' }
)
</script>
